services:
  mongoDB:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongoDB

volumes:
  mongo-data:
